import { describe, it, expect } from "vitest";
import fc from "fast-check";
import * as Y from "yjs";
import {
  MAX_AGENTS_PER_WORKSPACE,
  type ArtifactSnapshot,
  type Participant,
  type Workspace,
} from "@maw/shared";
import { InMemoryWorkspaceStore } from "../store/index.js";
import { RoomManager } from "./index.js";

// Feature: multiplayer-agent-workspace, Property 10: Agent add/remove round-trip
//
// For any workspace with fewer than five agents, adding an agent and then
// removing it returns the participant set and agent count to their prior
// values; removing an agent that is not a participant is rejected with an
// error and leaves the roster unchanged.
//
// Validates: Requirements 4.1, 4.4, 4.6
//
// We drive an arbitrary sequence of roster operations (add, remove-known,
// add/remove round-trip, remove-unknown) against a real RoomManager over an
// in-memory store, maintaining a reference set of the agent ids we expect to
// be present. After every operation we assert the live roster's agent-id set
// equals the reference set. Round-trip ops snapshot the full participant set +
// agent count, add then immediately remove an agent, and assert both are
// restored exactly. Unknown-removal ops target ids that are never in the roster
// and assert `AGENT_NOT_FOUND` with the roster left unchanged.

/** Encode an empty artifact Y.Doc state (mirrors WorkspaceService). */
function emptyArtifactState(): Uint8Array {
  const doc = new Y.Doc();
  doc.getText("content");
  const state = Y.encodeStateAsUpdate(doc);
  doc.destroy();
  return state;
}

/** Seed a workspace (owner + empty artifact) directly into the store. */
async function seedWorkspace(
  store: InMemoryWorkspaceStore,
  workspaceId: string,
  ownerId: string,
): Promise<void> {
  const workspace: Workspace = {
    id: workspaceId,
    joinReference: `${workspaceId}-ref`,
    ownerId,
    artifactId: `${workspaceId}-artifact`,
    createdAt: 1_000,
  };
  const owner: Participant = {
    id: ownerId,
    workspaceId,
    type: "human",
    displayName: "Owner",
    joinedAt: 1_000,
    presenceState: "active",
  };
  const artifact: ArtifactSnapshot = {
    id: workspace.artifactId,
    workspaceId,
    artifactType: "plan",
    content: "",
    lastEditorId: null,
    lastEditedAt: null,
    yjsState: emptyArtifactState(),
  };
  await store.createWorkspace({ workspace, owner, artifact });
}

/** A deterministic, incrementing agent-id generator. */
function makeIds(prefix = "agent"): () => string {
  let n = 0;
  return () => `${prefix}-${n++}`;
}

/** Sorted list of all participant (human + agent) ids currently in the room. */
function fullRosterIds(rm: RoomManager, workspaceId: string): string[] {
  return rm
    .getRoster(workspaceId)
    .map((p) => p.id)
    .sort();
}

/** Sorted list of just the agent-participant ids currently in the room. */
function agentRosterIds(rm: RoomManager, workspaceId: string): string[] {
  return rm
    .getRoster(workspaceId)
    .filter((p) => p.type === "agent")
    .map((p) => p.id)
    .sort();
}

// A roster operation. Ids of real agents are chosen reactively (they are
// generated by the RoomManager), so ops carry only relative selectors:
//  - `add`: add a persistent agent (if under the cap).
//  - `removeKnown`: remove an existing agent chosen by index.
//  - `roundTrip`: add then immediately remove one agent.
//  - `removeUnknown`: remove a fabricated id that is never in the roster.
const opArb = fc.oneof(
  fc.record({ kind: fc.constant("add" as const), displayName: fc.string() }),
  fc.record({ kind: fc.constant("removeKnown" as const), pick: fc.nat() }),
  fc.record({
    kind: fc.constant("roundTrip" as const),
    displayName: fc.string(),
  }),
  // Ghost ids are prefixed so they can never collide with generated `agent-*`
  // ids or the `owner-1` human, guaranteeing they are non-participants.
  fc.record({
    kind: fc.constant("removeUnknown" as const),
    ghost: fc.string(),
  }),
);

describe("Property 10: Agent add/remove round-trip", () => {
  it("restores the participant set and count on round-trip and rejects unknown removals leaving the roster unchanged", async () => {
    // **Validates: Requirements 4.1, 4.4, 4.6**
    await fc.assert(
      fc.asyncProperty(
        fc.array(opArb, { minLength: 1, maxLength: 40 }),
        async (ops) => {
          const store = new InMemoryWorkspaceStore();
          const workspaceId = "ws-1";
          const ownerId = "owner-1";
          await seedWorkspace(store, workspaceId, ownerId);

          const rm = new RoomManager(store, {
            now: () => 2_000,
            newId: makeIds("agent"),
          });
          await rm.ensureRoom(workspaceId);
          await rm.registerHuman(workspaceId, {
            id: ownerId,
            workspaceId,
            type: "human",
            displayName: "Owner",
            joinedAt: 1_000,
            presenceState: "active",
          });

          // Reference set of agent ids expected to be present in the roster.
          const expectedAgents = new Set<string>();

          for (const op of ops) {
            switch (op.kind) {
              case "add": {
                const atCap =
                  expectedAgents.size >= MAX_AGENTS_PER_WORKSPACE;
                const beforeFull = fullRosterIds(rm, workspaceId);
                const result = await rm.addAgent(workspaceId, {
                  displayName: op.displayName,
                });
                if (atCap) {
                  // The capacity guard rejects and adds nothing.
                  expect(result).toEqual({
                    ok: false,
                    error: "AGENT_LIMIT_REACHED",
                  });
                  expect(fullRosterIds(rm, workspaceId)).toEqual(beforeFull);
                } else {
                  expect(result.ok).toBe(true);
                  if (!result.ok) return false;
                  expectedAgents.add(result.participant.id);
                }
                break;
              }

              case "removeKnown": {
                if (expectedAgents.size === 0) break;
                const ids = [...expectedAgents];
                const target = ids[op.pick % ids.length]!;
                const result = await rm.removeAgent(workspaceId, target);
                expect(result.ok).toBe(true);
                if (!result.ok) return false;
                expect(result.agentId).toBe(target);
                expectedAgents.delete(target);
                break;
              }

              case "roundTrip": {
                // Snapshot the prior participant set + agent count.
                const priorFull = fullRosterIds(rm, workspaceId);
                const priorAgents = agentRosterIds(rm, workspaceId);
                const priorCount = rm.countAgents(workspaceId);
                const atCap =
                  expectedAgents.size >= MAX_AGENTS_PER_WORKSPACE;

                const added = await rm.addAgent(workspaceId, {
                  displayName: op.displayName,
                });

                if (atCap) {
                  // At the cap the add is rejected; the roster is unchanged,
                  // which is itself the round-trip invariant (no-op).
                  expect(added).toEqual({
                    ok: false,
                    error: "AGENT_LIMIT_REACHED",
                  });
                } else {
                  expect(added.ok).toBe(true);
                  if (!added.ok) return false;
                  // The agent is present after the add.
                  expect(rm.countAgents(workspaceId)).toBe(priorCount + 1);

                  const removed = await rm.removeAgent(
                    workspaceId,
                    added.participant.id,
                  );
                  expect(removed.ok).toBe(true);
                  if (!removed.ok) return false;
                }

                // Add-then-remove (or a rejected add) restores the prior set,
                // agent set, and agent count exactly.
                expect(fullRosterIds(rm, workspaceId)).toEqual(priorFull);
                expect(agentRosterIds(rm, workspaceId)).toEqual(priorAgents);
                expect(rm.countAgents(workspaceId)).toBe(priorCount);
                break;
              }

              case "removeUnknown": {
                const ghostId = `ghost-${op.ghost}`;
                const priorFull = fullRosterIds(rm, workspaceId);
                const priorCount = rm.countAgents(workspaceId);

                const result = await rm.removeAgent(workspaceId, ghostId);

                // A non-participant removal is rejected and changes nothing.
                expect(result).toEqual({
                  ok: false,
                  error: "AGENT_NOT_FOUND",
                });
                expect(fullRosterIds(rm, workspaceId)).toEqual(priorFull);
                expect(rm.countAgents(workspaceId)).toBe(priorCount);
                break;
              }
            }

            // Invariant after every op: the live agent roster equals the
            // reference set of agent ids, and the count agrees.
            expect(agentRosterIds(rm, workspaceId)).toEqual(
              [...expectedAgents].sort(),
            );
            expect(rm.countAgents(workspaceId)).toBe(expectedAgents.size);
          }

          return true;
        },
      ),
      { numRuns: 200 },
    );
  });
});
